### ISSUE TITLE
Data sources unavailable to public

### ISSUE THREAD

**Issue by mmb295** [department-of-veterans-affairs/va-data#11]
Hello,
I am requesting the best practice to gain access to some of the restricted data sets. I realize that privacy compliance will be the biggest issue, but how can I go about either gaining access or approval. The primary data sets that I would like to explore:
1. National Patient Care Database (NPCD)
2. National Mental Health Database System (NMHDS)
3. Health Data Repository (HDR)
4. Behavioral Health Autopsy Program (BHAP)
5. Corporate Data Warehouse (CDW)
6. Traumatic Brain Injury Registry (TBI)

I am conducting research, using analytics tools, to try and drive insights about veterans suffering from PTSD and TBI. 

Thank you.

**Comment by WateredTrees** [comment]
Visit http://www.hsrd.research.va.gov/for_researchers/vinci/default.cfm

**Comment by QJF3** [comment]
@mmb295,  you request covers some really large databases all of which contain Veteran identifying information, so there is no access to the data from outside of VA.   Even if you submitted a FOIA request to the VA (I am an employee), I believe the VHA FOIA Office would only approve aggregate reports from the sources you have listed, but not individual records, and many of those reports would have to built to address the specific search criteria you would need to specify.  As VA continually improves its data analytical capabilities, some IT systems are replaced with newer systems.   For instance, asking for National Patient Care Database, really VA's outpatient diagnosis and procedure information associated with outpatient visits, is not necessary because the content, in a more robust form, is available in the Corporate Data Warehouse. 

One could gain access to the data sets if you are part of an approved Institution Review Board scientific study.  If that approval came from within VA, then @WateredTrees suggestion to browse VINCI works.  If the Institution Review Board came from outside of VA, we can work with you to submit your application to the VA Under Secretary for Health for potential approval.

**Comment by mmb295** [comment]
@QJF3 

I am not apart of an approved Institution Review Board scientific study. I would like to work with you to try and gain access to VINCI through the VA Under Secretary for Health. 

I would prefer to try and gain access to individualized reports, but am also interested in aggregate reports. 

Please let me know what next steps that you suggest I take. I truly appreciate you reaching back and assisting in this matter.

**Comment by QJF3** [comment]
@mmb295
  The Under Secretary for Health process is for the advancement of generalized knowledge (research) that requires the approval of an Institutional Review Board (IRB).  This whole process is governed by law because it involves patient data and therefore human subjects.  From what you have written, the process through the Under Secretary for Health is not available.  Unless you are a VA employee or VA contractor on the VA network, including additional personnel requirements, VA can't  grant you access to the VA network and so VA cannot grant you access to VINCI.

If you can describe more of what you are seeking in reports, I can try to find if we have either posted something on the Internet (hopefully catalogued in Data.Gov) or have released information through FOIA.   If we don't have content available on the Internet already, then I can check with the FOIA Officer to determine if VA has released something already that could be made public.  Otherwise, we have to submit a FOIA request and that has its own process and queue.

Again, the more specific you can be the better.  This includes ICD-9 and ICD-10 codes or other specific search criteria such as period of service (WWII, Korea, Vietnam, Persian Gulf, Operation Enduring Freedom, Operation Iraqi Freedom).

**Comment by mmb295** [comment]
@QJF3 
Thank you for the information. I am conducting research as part of a bigger project with Academic Medical Centers and a non-profit organization. I am willing to explain more, but would prefer a less public forum.. can you email me at mmb295@cornell.edu?

I am basically looking for any data surrounding veterans and mental health issues after deployment (PTSD, TBI, etc.). The study will focus primarily on veterans from the Persian Gulf, OEF, and OIF. 

Listed below are the datasets that I found in the data.gov repository. 
•         Health Data Repository (HDR)
•         National Patient Care Database (NPCD)
•         National Mental Health Database System (NMHDS)
•         VA National Clozapine Registry
•         Traumatic Brain Injury Registry (TBI)

I should also mention that I am a part of a HIPAA compliant/covered entity. Please let me know what further steps I should take, and please reach out to me directly so that I can offer more detailed information. 

Thank you for your time.

**Comment by jalbertbowden** [comment]
what's the process/requirements for becoming a contractor?
not being cute, wondering what it would take to get access.....

**Comment by QJF3** [comment]
@mmb295 
I reached out to you from VA email account.

@jalbertbowden 
 To become a VA contractor, you have to work for a company that bids on VA work through the very structured federal acquisition process.   The important point is the company and its employees are accomplishing specific tasks required by VA.  So yes, contractors do have access to the VA network and VA's data, when appropriate, but only for specific reasons that VA enumerates in a contract.  Sorry if I mislead you into believing that you could have access to VA's health data for analysis just by becoming a contractor.   The VA contract would have to have that as a specific task.   You can search for opportunities at https://www.fbo.gov/.

**Comment by jalbertbowden** [comment]
@QJF3 you didn't mislead me @ all, but i appreciate it! thanks for tolerating the peanut gallery question...was pretty sure it wasn't wide open, just wanted to test the waters to make sure. thanks for the in-depth response, again, i appreciate it.
